-- Run this in the Supabase SQL Editor

create table subjects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  questions jsonb not null default '[]'::jsonb
);

-- Enable Row Level Security (RLS) if you want to restrict who can edit
-- For this simple public app, we might want to allow anyone to read/write
alter table subjects enable row level security;

-- Policy: Allow ANYONE to select (read)
create policy "Enable read access for all users"
on subjects for select
to anon
using (true);

-- Policy: Allow ANYONE to insert (add new subjects)
create policy "Enable insert for all users"
on subjects for insert
to anon
with check (true);

-- Policy: Allow ANYONE to update (add questions to existing)
create policy "Enable update for all users"
on subjects for update
to anon
using (true);

-- Policy: Allow ANYONE to delete (optional, maybe unsafe for public?)
create policy "Enable delete for all users"
on subjects for delete
to anon
using (true);
